---
title: Freedom Tour 2021
email: freedomtour21@gmail.com
description: |-
  The Freedom Tour was a Summer campaign, travelling through the UK, aiming to connect and grow the wider movement for a democratic, ecological and sane society. It aims to achieve this through street canvassing and hosting "Crisis Talk" community events.
  The team behind it is currently in reflection after 8 weeks on the road. Stay tuned for our next exploits.
logo: "/assets/images/logo-rect.png"
logo_square: "/assets/images/avatar.png"
logo_light: "/assets/images/logo-rect-light.png"
twitter: https://twitter.com/freedomtour21
instagram: https://www.instagram.com/freedomtour21/
copyright_notice: Made with love from Website's Dissent.
brand_color: "#0f529b"
accent_color: "#daa6c7"
baseurl: ''
url: https://freedomtour.uk
permalink: pretty
csv:
  route:
    source: https://docs.google.com/spreadsheets/d/17KfgdSAuRsU_VMeuVPalhWAn1LqCBMw-WSqaTMTYpmk/export?format=csv&gid=0
    slug: lng
defaults:
- scope:
    path: ''
  values:
    image: "/assets/images/og-preview.png"
- scope:
    path: google1c899b51019de383.html
  values:
    sitemap: false
- scope:
    path: admin/index.html
theme: jekyll-rebellion
collections:
  posts:
    permalink: "/news/:year/:month/:day/:slug"
plugins:
- jekyll-feed
- jekyll-leaflet
- jekyll-liquify
locale: en_gb
